### ISSUE TITLE
1.0.0 release can't be successfully loaded

### ISSUE THREAD

**Issue by cwjohnston** [sensu-extensions/sensu-extensions-check-dependencies#6]
Seems we've shipped 1.0.0 in an unusable state:

```
{
  "timestamp": "2017-03-15T15:45:43.541849+0000",
  "level": "warn",
  "message": "requiring extension gem",
  "require": "sensu/extensions/check-dependencies"
}
{
  "timestamp": "2017-03-15T15:45:43.541889+0000",
  "level": "warn",
  "message": "failed to require extension",
  "gem": "sensu-extensions-check-dependencies",
  "version": "1.0.0",
  "error": {
    "path": "sensu/extensions/check-dependencies",
    "~bt_locations": "#<Thread::Backtrace:0x00000000c71b68>",
    "~mesg": "cannot load such file -- sensu/extensions/check-dependencies",
    "~bt": [
      "/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'",
      "/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'",
      "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-extensions-1.7.1/lib/sensu/extensions/loader.rb:115:in `load_gem'",
      "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-extensions-1.7.1/lib/sensu/extensions.rb:30:in `block in load'",
      "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-extensions-1.7.1/lib/sensu/extensions.rb:28:in `each'",
      "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-extensions-1.7.1/lib/sensu/extensions.rb:28:in `load'",
      "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-extensions-1.7.1/lib/sensu/extensions.rb:44:in `get'",
      "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.28.4/lib/sensu/daemon.rb:157:in `load_extensions'",
      "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.28.4/lib/sensu/daemon.rb:58:in `initialize'",
      "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.28.4/lib/sensu/server/process.rb:42:in `initialize'",
      "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.28.4/lib/sensu/server/process.rb:30:in `new'",
      "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.28.4/lib/sensu/server/process.rb:30:in `run'",
      "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.28.4/exe/sensu-server:10:in `<top (required)>'",
      "/opt/sensu/bin/sensu-server:22:in `load'",
      "/opt/sensu/bin/sensu-server:22:in `<main>'"
    ]
  }
}
```

**Comment by cwjohnston** [comment]
In 95f3933f173af8c860781c8990d54c289d1bbd7c we renamed the project but not the extension Ruby file.
